openapi: 3.0.0
info:
    title: "Sign REST API"
    description: Api for structure
    version: v1.0
servers:
    -   url: /rest
        description: Local server

tags:
    -   name: "download"
        description: "Downloading signed documents"
    -   name: "provider"
        description: "Third party signing providers"
paths:
    /sign.b2e.mysafe.tail:
        get:
            summary: List of signed documents for downloading
            tags:
                - "download"
            parameters:
                -   in: query
                    name: limit
                    description: limit
                    required: false
                    schema:
                        type: integer
                        minimum: 1
                        default: 20
                        maximum: 1000
                -   in: query
                    name: offset
                    description: offset
                    required: false
                    schema:
                        type: integer
                        minimum: 0
                        default: 0

            responses:
                200:
                    $ref: '#/components/responses/MySafeTailResponse'
                401:
                    $ref: '#/components/responses/AuthErrorResponse'

    /sign.b2e.personal.tail:
        get:
            summary: List user signed documents
            tags:
                - "download"
            parameters:
                -   in: query
                    name: limit
                    description: limit
                    required: false
                    schema:
                        type: integer
                        minimum: 1
                        default: 20
                        maximum: 1000
                -   in: query
                    name: offset
                    description: offset
                    required: false
                    schema:
                        type: integer
                        minimum: 0
                        default: 0

            responses:
                200:
                    $ref: '#/components/responses/PersonalTailResponse'
                401:
                    $ref: '#/components/responses/AuthErrorResponse'

    /sign.b2e.provider.add:
        post:
            summary: Add new external sign provider
            tags:
                - "provider"
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            type: object
                            properties:
                                fields:
                                    $ref: "#/components/schemas/ProviderFields"


            responses:
                200:
                    description: Id of added provider
                    content:
                        application/json:
                            schema:
                                type: object
                                properties:
                                    result:
                                        type: integer
                                        description: id of added provider
                                        example: 42
                                    time:
                                        $ref: "#/components/schemas/DebugTime"


                401:
                    $ref: '#/components/responses/AuthErrorResponse'

    /sign.b2e.provider.update:
        post:
            summary: Change external sign provider
            tags:
                - "provider"
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            type: object
                            properties:
                                id:
                                    description: id
                                    type: integer
                                    minimum: 1
                                    default: 1
                                fields:
                                    $ref: "#/components/schemas/ProviderFields"


            responses:
                200:
                    description: Result of operation
                    content:
                        application/json:
                            schema:
                                type: object
                                properties:
                                    result:
                                        type: boolean
                                        description: result of saving
                                        example: true
                                    time:
                                        $ref: "#/components/schemas/DebugTime"


                401:
                    $ref: '#/components/responses/AuthErrorResponse'


    /sign.b2e.provider.delete:

        post:
            tags:
                - "provider"
            summary: Delete external sign provider
            requestBody:
                required: true
                content:
                    application/x-www-form-urlencoded:
                        schema:
                            type: object
                            properties:
                                id:
                                    description: id
                                    type: integer
                                    minimum: 1
                                    default: 1

            responses:
                200:
                    description: Result of operation
                    content:
                        application/json:
                            schema:
                                type: object
                                properties:
                                    result:
                                        type: boolean
                                        description: result of deleting
                                        example: true
                                    time:
                                        $ref: "#/components/schemas/DebugTime"


                401:
                    $ref: '#/components/responses/AuthErrorResponse'

    /sign.b2e.provider.tail:
        get:
            summary: List of external sign providers
            tags:
                - "provider"
            parameters:
                -   in: query
                    name: limit
                    description: limit
                    required: false
                    schema:
                        type: integer
                        minimum: 1
                        default: 20
                        maximum: 1000
                -   in: query
                    name: offset
                    description: offset
                    required: false
                    schema:
                        type: integer
                        minimum: 0
                        default: 0

            responses:
                200:
                    $ref: '#/components/responses/ProvidersResponse'

                401:
                    $ref: '#/components/responses/AuthErrorResponse'

security:
    -   token: [ ]
    -   xdebug: [ ]

components:
    securitySchemes:
        token:
            type: apiKey
            in: query
            name: auth
            description: Token
        xdebug:
            type: apiKey
            in: cookie
            name: XDEBUG_SESSION
            description: XDebug

    responses:
        MySafeTailResponse:
            description: My safe list of documents
            content:
                application/json:
                    schema:
                        type: object
                        properties:
                            result:
                                type: array
                                items:
                                    type: object
                                    properties:
                                        id:
                                            type: integer
                                        title:
                                            type: string
                                            description: document title
                                            example: Signed_document_1
                                        create_date:
                                            type: string
                                            description: date in ISO-8601
                                            example: 2005-08-15T15:52:01+03:00
                                        signed_date:
                                            type: string
                                            description: date in ISO-8601
                                            example: 2005-08-15T15:52:01+03:00
                                        creator_id:
                                            type: integer
                                            description: bitrix userId
                                        member_id:
                                            type: integer
                                            description: bitrix userId
                                        role:
                                            # @see  \Bitrix\Sign\Type\Member\Role
                                            enum:
                                                - editor
                                                - reviewer
                                                - assignee
                                                - signer
                                        file_url:
                                            type: string
                                            description: link to download file
                                            example: "https://.../rest/download.json?auth=...&token=..."
                            time:
                                $ref: "#/components/schemas/DebugTime"

        PersonalTailResponse:
            description: My safe list of documents
            content:
                application/json:
                    schema:
                        type: object
                        properties:
                            result:
                                type: array
                                items:
                                    type: object
                                    properties:
                                        id:
                                            type: integer
                                        title:
                                            type: string
                                            description: document title
                                            example: Signed_document_1
                                        signed_date:
                                            type: string
                                            description: date in ISO-8601
                                            example: 2005-08-15T15:52:01+03:00
                                        file_url:
                                            type: string
                                            description: link to download file
                                            example: "https://.../rest/download.json?auth=...&token=..."
                            time:
                                $ref: "#/components/schemas/DebugTime"

        ProvidersResponse:
            description: List of external providers
            content:
                application/json:
                    schema:
                        type: object
                        properties:
                            result:
                                type: array
                                items:
                                    allOf:
                                        -   type: object
                                            properties:
                                                id:
                                                    type: integer
                                                    example: 1
                                        - $ref: "#/components/schemas/ProviderFields"

                            time:
                                $ref: "#/components/schemas/DebugTime"

        ErrorResponse:
            description: Error
            content:
                application/json:
                    schema:
                        $ref: '#/components/schemas/ErrorResponse'

        AuthErrorResponse:
            description: Authentication error
            content:
                application/json:
                    schema:
                        $ref: '#/components/schemas/AuthErrorResponse'

    schemas:
        ProviderFields:
            type: object
            properties:
                title:
                    description: title
                    type: string
                    example: "Test provider name"
                description:
                    description: description
                    type: string
                    example: "Brief text about provider"
                iconUri:
                    description: icon for interface
                    type: string
                    example: "https://provider.sign.com/bitrix/icon.png"
                companyRegUri:
                    description: Page for registration
                    type: string
                    example: "https://provider.sign.com/bitrix/register/"
                documentSignUri:
                    description: Page for signing
                    type: string
                    example: "https://provider.sign.com/bitrix/sign/"
                publicKeyUri:
                    description: Public key
                    type: string
                    example: "https://provider.sign.com/bitrix/public.key"

        ErrorResponse:
            type: object
            properties:
                error:
                    type: string
                error_description:
                    type: string

        AuthErrorResponse:
            allOf:
                -   $ref: '#/components/schemas/ErrorResponse'
                -   type: object
                -   properties:
                        error:
                            default: 'NO_AUTH_FOUND'
                        error_description:
                            default: 'Wrong authorization data'

        DebugTime:
            type: object
            properties:
                start:
                    type: number
                    format: double
                    description: Unix timestamp with milliseconds
                    example: "1721140793.148319"
                finish:
                    type: number
                    format: double
                    description: Unix timestamp with milliseconds
                    example: "1721140793.148319"
                duration:
                    type: number
                    format: double
                    description: Time in seconds
                    example: "0.01234567890123"
                processing:
                    type: number
                    format: double
                    description: Time in seconds
                    example: "0.01234567890123"
                date_start:
                    type: string
                    format: double
                    description: Timestamp ISO 8601
                    example: "1970-01-01T14:39:53+00:00"
                date_finish:
                    type: string
                    format: double
                    description: Timestamp ISO 8601
                    example: "1970-01-01T14:39:53+00:00"
